// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasteringEfDemo.Models;

public partial class VSalesPersonSalesByFiscalYear
{
    public int? SalesPersonId { get; set; }

    public string FullName { get; set; }

    public string JobTitle { get; set; }

    public string SalesTerritory { get; set; }

    public decimal? _2002 { get; set; }

    public decimal? _2003 { get; set; }

    public decimal? _2004 { get; set; }
}